image: node:latest
before_script:
  - npm ci --also=dev

.rules-default-and-merge-train: &rules-default-and-merge-train
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_request"'
    - if: '$CI_COMMIT_REF_NAME == "master"'

stages:
  - test
  - check-coverage

test:
  stage: test
  <<: *rules-default-and-merge-train
  variables:
    LOG_LEVEL: ERROR
  script:
    - npm test
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

lint:
  stage: test
  <<: *rules-default-and-merge-train
  script:
    - npm run lint:check

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  before_script: []
  artifacts:
    paths: [gl-code-quality-report.json]
