image: node:latest
before_script:
  - npm ci --also=dev

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - .nyc_output
    expire_in: 1 day

coverage:
  stage: deploy
  needs:
    - test
  script:
    - npm run cobertura-coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
    paths:
      - coverage
    expire_in: 30 days